print("Mother to Son  By Langston Hughes \n"
"Well, son, I'll tell you: \n"
"Life for me ain't been no crystal stair. \n"
"It's had tacks in it, \n"
"And splinters, \n"
"And boards torn up, \n"
"And places with no carpet on the floor- \n"
"Bare. \n"
"But all the time \n"
"I'se been a-climbin' on, \n"
"And reachin' landin's, \n"
"And turnin' corners, \n"
"And sometimes goin' in the dark \n"
"Where there ain't been no light. \n"
"So boy, don't you turn back. \n"
"Don't you set down on the steps \n"
"'Cause you finds it's kinder hard. \n"
"Don't you fall now- \n"
"For I'se still goin', honey, \n"
"I'se still climbin', \n"
"And life for me ain't been no crystal stair.")
